FROM node:25.6.0-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  procps \
  curl \
  ffmpeg \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app

USER node

CMD ["npx", "ts-node", "-r", "tsconfig-paths/register", "worker/src/main.ts"]
